# Default values for prometheus-redis-exporter

image:
  repository: oliver006/redis_exporter
  tag: v1.61.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9121
  annotations: {}

# Redis target to monitor
# Format: redis://host:port
redisAddress: "redis://redis-prod-master.redis-prod-svc:6379"

# If Redis requires a password
# redisPassword: "yourpassword"

# SecurityContext
securityContext:
  runAsNonRoot: true
  runAsUser: 65534

resources: {}
# requests:
#   cpu: 100m
#   memory: 128Mi
# limits:
#   cpu: 200m
#   memory: 256Mi

serviceMonitor:
  enabled: true
  namespace: monitoring
  interval: 30s
  scrapeTimeout: 10s
  labels: {}
  annotations: {}
  honorLabels: false

# PrometheusRule (if you want default alerts)
prometheusRule:
  enabled: false

rbac:
  create: true
  pspEnabled: false

# Extra env vars for exporter
extraEnv: []
